// <auto-generated />
using IBM.EntityFrameworkCore;
using IBM.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication4;

namespace WebApplication4.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseDb2IdentityColumns()
                .HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("WebApplication4.Models.Habit", b =>
                {
                    b.Property<int>("HabitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseDb2IdentityColumn();

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("DailyCompletion")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(32672)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyCompletion")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32672)");

                    b.Property<int>("YearlyCompletion")
                        .HasColumnType("int");

                    b.HasKey("HabitId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("WebApplication4.Models.HabitReward", b =>
                {
                    b.Property<int>("HabitId")
                        .HasColumnType("int");

                    b.Property<int>("RewardId")
                        .HasColumnType("int");

                    b.HasKey("HabitId", "RewardId");

                    b.HasIndex("RewardId");

                    b.ToTable("HabitRewards");
                });

            modelBuilder.Entity("WebApplication4.Models.Reward", b =>
                {
                    b.Property<int>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseDb2IdentityColumn();

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(32672)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32672)");

                    b.HasKey("RewardId");

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("WebApplication4.Models.HabitReward", b =>
                {
                    b.HasOne("WebApplication4.Models.Habit", "Habits")
                        .WithMany("HabitRewards")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication4.Models.Reward", "Rewards")
                        .WithMany("HabitRewards")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habits");

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("WebApplication4.Models.Habit", b =>
                {
                    b.Navigation("HabitRewards");
                });

            modelBuilder.Entity("WebApplication4.Models.Reward", b =>
                {
                    b.Navigation("HabitRewards");
                });
#pragma warning restore 612, 618
        }
    }
}
